### ISSUE TITLE
Fix the bug of 4.0+

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [BUGProtectionAssociation/Blender-Text-Editor-Essentials-reborn#1]
Fix type error
```
Traceback (most recent call last):
  File "\addons\Blender-Text-Editor-Essentials\code_editor.py", line 1091, in <lambda>
    bpy.app.timers.register(lambda: timer(func, *args, init=True),
  File "\addons\Blender-Text-Editor-Essentials\code_editor.py", line 1089, in timer
    func(*args)
TypeError: _bpy.ops.call() argument 3 must be str, not dict
```

**Comment by BUGProtectionAssociation** [comment]
#2 Have a try?
